name: Deploy the website

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server 1
              run: |
                  ssh -o StrictHostKeyChecking=no -t root@134.209.238.57 <<EOF
                  git config --global --add safe.directory /app
                  cd /app
                  git pull origin main .
                  python -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt
                  python manage.py collectstatic --noinput
                  EOF
