name: Deploy the website

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server 1
              run: |
                  ssh -o StrictHostKeyChecking=no root@134.209.238.57 <<EOF
                  set -e

                  # Ensure /app exists
                  if [ ! -d /app ]; then
                      mkdir -p /app
                  fi

                  cd /app

                  # Add GitHub to known hosts
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

                  # Clone if missing, else pull updates
                  if [ ! -d ".git" ]; then
                      git clone git@github.com:nodarisvanidze88/week_23_ecommerce.git .
                  else
                      git pull origin main
                  fi

                  # Set Git safe directory
                  git config --global --add safe.directory /app

                  # Set up virtual environment
                  sudo apt update
                  sudo apt install -y python3-venv python3-pip
                  python3 -m venv venv
                  source venv/bin/activate

                  # Upgrade pip and install dependencies
                  pip install --upgrade pip
                  pip install -r requirements.txt

                  # Collect static files
                  python manage.py collectstatic --noinput

                  # Restart Gunicorn
                  sudo systemctl restart gunicorn
                  EOF
